language: python

addons:
  apt:
    packages:
    - xvfb
    - herbstluftwm
    - libssl-dev
    - openssl
    - libacl1-dev
    - libacl1
    - build-essential
    - golang
    - git

sudo: required
dist: xenial

python:
  - "3.6"

env:
  global:
  - SETUP_XVFB=true

matrix:
  include:
  - os: linux
    dist: xenial
    env:
    - RUN_PYINSTALLER=true

install:
- "export DISPLAY=:99.0"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
- sleep 3


- python3 -m pip install -U setuptools pip
- python3 -m pip install .
- python3 -m pip install -r requirements-dev.txt

- wget https://github.com/restic/restic/releases/download/v0.9.3/restic_0.9.3_linux_amd64.bz2
- bzcat restic_0.9.3_linux_amd64.bz2 > bin/restic
- chmod +x bin/restic

before_script:
- export PATH=$PATH:$PWD/bin/
- "herbstluftwm &"
- sleep 3


script:
- pytest --forked
- tox -e flake8

#after_script:
#- |
#  if [ $RUN_PYINSTALLER = "true" ]; then
#    # Cleanup
#    pip uninstall -y $PIP_DEPENDENCIES
#
#    # https://github.com/wkentaro/labelme/issues/183
#    if [ $TRAVIS_OS_NAME = "osx" ]; then
#      pip uninstall -y Pillow
#      conda install -y Pillow
#    fi
#
#    # Build the standalone executable
#    pip install pyinstaller
#    pyinstaller labelme.spec
#    dist/labelme --version
#  fi

branches:
  only:
  - gh-pages
  - /.*/

notifications:
  email: false

cache:
  directories:
  - $HOME/.cache/pip
